# Generated by Django 4.0.4 on 2022-11-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_charcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charcard',
        ),
    ]
