# Generated by Django 4.0.4 on 2022-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_delete_charcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
