# Generated by Django 4.0.4 on 2022-11-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcard_difficulty_flashcard_mnemonic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty',
        ),
    ]
