# Generated by Django 4.0.4 on 2022-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_remove_flashcard_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
