# Generated by Django 4.0.4 on 2022-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_flashcard_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='question',
            new_name='question',
        ),
    ]
