# Generated by Django 4.1.3 on 2022-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_rename_character_flashcard_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='pinyin',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
